name: CI

on:
  push:
    branches:
      - develop
      - master
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v5

      - run: corepack enable

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - run: npm ci

      - run: npm run lint

      - run: npm run test
